import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

import { Button } from "@/components/ui/button";
import { NavMenu } from "@/components/nav/nav-menu";
import { MobileNav } from "@/components/nav/mobile-nav";

import Logo from "@/public/logo.svg";

import Image from "next/image";
import Link from "next/link";

import { cn } from "@/lib/utils";

const fontSans = localFont({
  src: [
    {
      path: "../public/fonts/Parkinsans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Parkinsans-Medium.woff2", 
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Parkinsans-Bold.woff2",
      weight: "700", 
      style: "normal",
    },
    {
      path: "../public/fonts/Parkinsans-ExtraBold.woff2",
      weight: "900", 
      style: "normal",
    }
  ],
  variable: "--font-sans",
});

const parkinsons = localFont({
  src: "../public/fonts/Parkinsans-Regular.woff2",
  variable: "--font-parkinsons",
});

export const metadata: Metadata = {
  title: "Craft Next.js Starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen antialiased font-sans",
          fontSans.variable
        )}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}

const Nav = ({ className, children, id }: NavProps) => {
  return (
    <nav
      className={cn("sticky z-50 top-0 bg-background", "border-b", className)}
      id={id}
    >
      <div
        id="nav-container"
        className="max-w-5xl mx-auto py-4 px-6 sm:px-8 flex justify-between items-center"
      >
        <Link
          className="hover:opacity-75 transition-all flex gap-2 items-center"
          href="/"
        >
          <h2 className="sr-only">Trnava Region Innovates</h2>
          <Image
            src={Logo}
            alt="Logo"
            className=""
            width={84}
            height={30.54}
          ></Image>
        </Link>
        {children}
        <div className="flex items-center gap-2">
          <NavMenu />
          <Button asChild className="hidden rounded-full bg-blue-300 hover:bg-blue-600 text-white hover:text-grey-100 sm:flex">
            <Link href="#mail">Chcem byť súčasťou</Link>
          </Button>
          <MobileNav />
        </div>
      </div>
    </nav>
  );
};
