import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { LanguageProvider } from "@/components/nav/nav-switcher";
import { Nav } from "@/components/nav/nav";

const parkinsans = localFont({
  src: [
    {
      path: "../public/fonts/Parkinsans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Parkinsans-Medium.woff2", 
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Parkinsans-Bold.woff2",
      weight: "700", 
      style: "normal",
    },
    {
      path: "../public/fonts/Parkinsans-ExtraBold.woff2",
      weight: "900", 
      style: "normal",
    }
  ],
  variable: "--font-parkinsans",
});

const barlow = localFont({
  src: "../public/fonts/Barlow-Light.woff2",
  variable: "--font-barlow",
});

export const metadata: Metadata = {
  title: "Craft Next.js Starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen antialiased",
          barlow.variable,
          parkinsans.variable
        )}
      >
        <LanguageProvider>
          <Nav />
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
